### ISSUE TITLE
Creating objects

### ISSUE THREAD

**Issue by fingask** [Kravalg/mfiles-client#1]
Having an issue using **create_object** when creating a new object with properties specified.
This seems to be related to  **get_value_id** checking for a matching **owner_id** on the property being added before it will return an id:

```
  correct_owner = item["OwnerID"] in owner_ids
            if same_name and correct_owner:
                return item["ID"]
```

In this instance the property being added references an object that is not the owner of the object being created so I am unable to create the new object.

I'm new to the m-files web api so my apologies if I am missing in my reasoning?

**Comment by Kravalg** [comment]
At the moment, the library does not support the creation of objects. We would be grateful if you would prepare a PR with the appropriate functionality.

**Comment by fingask** [comment]
Apologies, had two windows open and logged in wrong one - must be all this time I'm spending indoors!
